<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="2009" started-at="2019-07-31T13:12:59Z" finished-at="2019-07-31T13:13:01Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="2009" started-at="2019-07-31T13:12:59Z" finished-at="2019-07-31T13:13:01Z">
      <class name="restAssuredUsingGit.test.Test3PS">
        <test-method status="PASS" signature="testCreatingNewEmployee()[pri:1, instance:restAssuredUsingGit.test.Test3PS@4501b7af]" name="testCreatingNewEmployee" duration-ms="1869" started-at="2019-07-31T13:12:59Z" finished-at="2019-07-31T13:13:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreatingNewEmployee -->
        <test-method status="PASS" signature="testUpdatingAnEmployee()[pri:2, instance:restAssuredUsingGit.test.Test3PS@4501b7af]" name="testUpdatingAnEmployee" duration-ms="32" started-at="2019-07-31T13:13:01Z" finished-at="2019-07-31T13:13:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdatingAnEmployee -->
        <test-method status="FAIL" signature="testAllEmployees()[pri:3, instance:restAssuredUsingGit.test.Test3PS@4501b7af]" name="testAllEmployees" duration-ms="45" started-at="2019-07-31T13:13:01Z" finished-at="2019-07-31T13:13:01Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[expected:<201> but was:<200>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: expected:<201> but was:<200>
at junit.framework.Assert.fail(Assert.java:50)
at junit.framework.Assert.failNotEquals(Assert.java:287)
at junit.framework.Assert.assertEquals(Assert.java:67)
at junit.framework.Assert.assertEquals(Assert.java:199)
at junit.framework.Assert.assertEquals(Assert.java:205)
at restAssuredUsingGit.test.Test3PS.testAllEmployees(Test3PS.java:35)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAllEmployees -->
        <test-method status="PASS" signature="testSpecificEmployee()[pri:4, instance:restAssuredUsingGit.test.Test3PS@4501b7af]" name="testSpecificEmployee" duration-ms="27" started-at="2019-07-31T13:13:01Z" finished-at="2019-07-31T13:13:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSpecificEmployee -->
      </class> <!-- restAssuredUsingGit.test.Test3PS -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
